(function(){
const categories=['safety','primary','emergency','priorities','anamnesis','followup','reassessment'];
class AnamnesisEngine{
 constructor(scenario){this.scenario=scenario;this.state={phase:'scene',actions:[],questions:[],facts:[],unlocked:[],events:[],criticalErrors:[],score:Object.fromEntries(categories.map(k=>[k,0])),interactions:0,patient:{consciousness:scenario.patient.consciousness},log:[]};}
 hasFact(id){return this.state.facts.includes(id)} didAction(id){return this.state.actions.includes(id)} asked(id){return this.state.questions.includes(id)}
 evaluate(c={}){if(!c||!Object.keys(c).length)return true;if(c.action&&!this.didAction(c.action))return false;if(c.question&&!this.asked(c.question))return false;if(c.fact&&!this.hasFact(c.fact))return false;if(c.interactionsAtLeast&&this.state.interactions<c.interactionsAtLeast)return false;if(c.missingFacts&&c.missingFacts.some(f=>this.hasFact(f)))return false;if(c.all&&!c.all.every(x=>this.evaluate(x)))return false;if(c.any&&!c.any.some(x=>this.evaluate(x)))return false;return true}
 addFacts(ids=[]){ids.forEach(id=>{if(!this.hasFact(id))this.state.facts.push(id)})} applyScore(s){if(s)this.state.score[s.category]=(this.state.score[s.category]||0)+s.points}
 allActions(){return [...this.scenario.actions,...this.scenario.primaryAssessment]}
 perform(id){const a=this.allActions().find(x=>x.id===id);if(!a||this.didAction(id))return {ok:false,message:'הפעולה כבר בוצעה.'};if((a.requires||[]).some(x=>!this.hasFact(x)))return {ok:false,message:'עדיין חסר מידע שמצדיק או מאפשר את הפעולה הזו.'};this.state.actions.push(id);this.state.interactions++;this.addFacts(a.reveals);this.applyScore(a.score);if(a.critical&&!this.state.criticalErrors.includes(id))this.state.criticalErrors.push(id);this.state.log.push({kind:a.critical?'bad':'action',text:a.result||a.label});this.processEvents();return {ok:true,message:a.result||'הפעולה בוצעה.'}}
 ask(id){const q=this.scenario.anamnesis.find(x=>x.id===id);if(!q||this.asked(id)||!this.isQuestionAvailable(q))return {ok:false,message:'השאלה אינה זמינה כעת.'};this.state.questions.push(id);this.state.interactions++;this.addFacts(q.reveals);this.applyScore(q.score);(q.unlocks||[]).forEach(x=>{if(!this.state.unlocked.includes(x))this.state.unlocked.push(x)});this.state.log.push({kind:(q.score?.points||0)<0?'bad':'answer',text:q.answer});this.processEvents();return {ok:true,message:q.answer,feedback:q.feedback}}
 isQuestionAvailable(q){return !this.asked(q.id)&&(!q.condition||this.evaluate(q.condition))}
 processEvents(){for(const e of this.scenario.events||[]){if(!this.state.events.includes(e.id)&&this.evaluate(e.trigger)){this.state.events.push(e.id);this.addFacts(e.change?.addFacts);if(e.change?.consciousness)this.state.patient.consciousness=e.change.consciousness;this.state.log.push({kind:'event',text:e.feedback})}}}
 getReport(){const all=this.allActions(),required=all.filter(a=>a.importance==='חובה'),missed=required.filter(a=>!this.didAction(a.id)),missedFacts=(this.scenario.expectedPath.requiredFacts||[]).filter(f=>!this.hasFact(f)),unnecessary=[...all.filter(a=>this.didAction(a.id)&&(a.importance==='מיותרת'||(a.score?.points||0)<0)),...this.scenario.anamnesis.filter(q=>this.asked(q.id)&&q.importance==='לא רלוונטית')],followups=this.scenario.anamnesis.filter(q=>q.condition&&!this.asked(q.id)&&this.evaluate(q.condition)),missedCritical=missed.filter(a=>a.criticalOmission).map(a=>a.id),critical=[...new Set([...this.state.criticalErrors,...missedCritical])],earned=Object.values(this.state.score).reduce((a,b)=>a+Math.max(0,b),0),max=Object.values(this.scenario.scoring.max).reduce((a,b)=>a+b,0),penalty=critical.length*8,percent=Math.max(0,Math.min(100,Math.round(earned/max*100-penalty)));return {percent,missed,missedFacts,unnecessary,followups,critical,score:this.state.score,max:this.scenario.scoring.max}}
}
window.AnamnesisEngine=AnamnesisEngine;
})();
