(function(){
const score=(category,points)=>({category,points});
const action=(id,label,group,importance,points,reveals=[],extra={})=>({id,label,group,importance,score:points,reveals,...extra});
const question=(id,text,category,answer,importance,points,reveals=[],extra={})=>({id,text,category,answer,importance,score:score('anamnesis',points),reveals,...extra});
window.SCENARIOS=[
{
 id:'hypoglycemia-01',internalName:'young-adult-hypoglycemia',category:'סוכרת והפרעת הכרה',difficulty:'מתחיל',duration:'8–10 דקות',
 learningObjectives:['ביצוע ABCDE בחולה עם שינוי התנהגות','זיהוי היפוגליקמיה באמצעות בדיקת סוכר','התאמת טיפול למצב ההכרה ויכולת הבליעה','הערכה חוזרת לאחר טיפול'],courseTopics:['2-1 אנמנזה וגישה לחולה','2-4 סוכרת ומצבי חירום גליקמיים'],
 scene:{dispatchReason:'חולשה והתנהגות חריגה',location:'דירת מגורים, קומה 2',shortDescription:'חברה פתחה את הדלת. המטופלת יושבת על הרצפה ונשענת על הספה.',patientCount:1,preArrivalInfo:'בת 24, בהכרה. לא דווח על חבלה.',immediateView:'המטופלת חיוורת ומזיעה, מביטה סביב באי־שקט ועונה באיחור.'},
 safety:{existingHazards:['מחט אינסולין משומשת על שולחן נמוך'],distractors:['אין ריח גז','אין בעלי חיים מאיימים'],ppe:['כפפות'],requiredActions:['ppe','scan-scene'],additionalResources:['ALS אם ההכרה מידרדרת או אין יכולת בליעה'],criticalMistakes:['unsafe-needle']},
 patient:{age:24,chiefComplaint:'חולשה, רעב ובלבול',consciousness:'ערנית אך מבולבלת, AVPU=A',behavior:'חסרת מנוחה ועונה באיחור',appearance:'חיוורת, קרה ולחה',findings:['ללא חבלה נראית לעין','משאבת אינסולין מחוברת'],vitals:{respiratoryRate:'18 בדקה, סדיר',pulse:'108 בדקה, מלא',bloodPressure:'112/72',spo2:'98%',glucose:'48 mg/dL'},history:{conditions:['סוכרת סוג 1'],medications:['אינסולין במשאבה'],allergies:'לא ידועות',lastMeal:'ארוחת בוקר קטנה לפני 7 שעות',events:'לקחה אינסולין כרגיל, דילגה על ארוחת צהריים והלכה ברגל'}},
 facts:{'gloves-on':'כפפות נלבשו','scene-safe':'הזירה בטוחה להתקרבות','syringe-seen':'נצפתה מחט אינסולין משומשת','insulin-pump-seen':'מחוברת משאבת אינסולין','airway-open':'נתיב האוויר פתוח; המטופלת מדברת','breathing-ok':'נשימה 18 בדקה, סדירה; סטורציה 98%','circulation':'דופק 108, מלא; ל״ד 112/72; עור קר ולח','neuro':'AVPU=A, מבולבלת, ללא חסר צדדי ברור','glucose-low':'סוכר 48 mg/dL','swallow-ok':'המטופלת ערנית, מצייתת ויכולה לבלוע','diabetes':'סוכרת סוג 1','missed-meal':'דילגה על ארוחת צהריים לאחר אינסולין והליכה','treated':'ניתן גלוקוז פומי לפי הפרוטוקול','improved':'כעבור דקות: ערנית ורגועה יותר; סוכר חוזר 82 mg/dL','als-called':'הוזעק צוות ALS','reassessed':'בוצעה הערכה חוזרת לאחר טיפול'},
 primaryAssessment:[
  action('airway','הערכת נתיב אוויר','primary','חובה',score('primary',8),['airway-open'],{order:1,criticalOmission:true,result:'המטופלת מדברת — נתיב האוויר פתוח.'}),
  action('breathing','הערכת נשימה וסטורציה','primary','חובה',score('primary',8),['breathing-ok'],{order:2,criticalOmission:true,result:'18 נשימות סדירות בדקה, סטורציה 98%.'}),
  action('circulation','דופק, עור ולחץ דם','primary','חובה',score('primary',7),['circulation'],{order:3,result:'דופק מהיר ומלא; העור חיוור, קר ולח.'}),
  action('neuro','הערכת הכרה ונוירולוגיה בסיסית','primary','חובה',score('primary',7),['neuro'],{order:4,result:'ערנית אך מבולבלת; אין חסר צדדי ברור.'}),
  action('glucose','בדיקת סוכר','primary','חובה',score('emergency',15),['glucose-low'],{order:5,criticalOmission:true,result:'48 mg/dL — היפוגליקמיה.'}),
  action('swallow','הערכת יכולת בליעה','primary','חובה',score('priorities',8),['swallow-ok'],{requires:['glucose-low'],result:'מצייתת, מגינה על נתיב האוויר ויכולה לבלוע.'})],
 anamnesis:[
  question('chief','מה מפריע לך עכשיו?','תלונה עיקרית','״אני חלשה ורועדת… וקשה לי להתרכז.״','חשובה',4,['symptoms']),
  question('onset','מתי זה התחיל?','מחלה נוכחית','״לפני בערך עשרים דקות, בדרך חזרה הביתה.״','חשובה',4,['sudden-onset']),
  question('conditions','יש לך מחלות רקע?','רקע רפואי','״סוכרת סוג 1.״','חשובה',5,['diabetes'],{unlocks:['insulin-details']}),
  question('insulin-details','לקחת אינסולין היום?','תרופות','״כן, כרגיל. המשאבה עובדת.״','חשובה',4,['insulin-taken'],{condition:{question:'conditions'},unlocks:['food','activity']}),
  question('food','מתי אכלת לאחרונה?','SAMPLE','״בבוקר. לא הספקתי לאכול צהריים.״','חשובה',6,['missed-meal'],{condition:{question:'insulin-details'}}),
  question('activity','היה מאמץ חריג?','מחלה נוכחית','״הלכתי כמעט שעה ברגל.״','משלימה',3,['exercise'],{condition:{question:'insulin-details'}}),
  question('allergy','יש רגישות לתרופות או למזון?','SAMPLE','״לא שידוע לי.״','משלימה',2,['no-known-allergy']),
  question('holiday','איפה תרצי לבלות בחופשה?','לא רלוונטי','״מה? אני לא מצליחה להתרכז.״','לא רלוונטית',-2,[],{feedback:'השאלה אינה מקדמת את ההערכה הרפואית.'})],
 actions:[
  action('ppe','לבישת כפפות','safety','חובה',score('safety',8),['gloves-on'],{result:'הצוות ממוגן.'}),action('scan-scene','סריקת הזירה וספירת מטופלים','safety','חובה',score('safety',7),['scene-safe','syringe-seen','insulin-pump-seen'],{result:'מטופלת אחת. אין סכנה פעילה; מחט משומשת על השולחן.'}),action('unsafe-needle','להרים את המחט ביד חשופה','safety','מיותרת',score('safety',-15),[],{critical:true,result:'סכנת דקירה וחשיפה ביולוגית.'}),
  action('oral-glucose','מתן גלוקוז פומי לפי הפרוטוקול','treatment','חובה',score('priorities',15),['treated'],{requires:['glucose-low','swallow-ok'],criticalOmission:true,result:'המטופלת מקבלת גלוקוז פומי תחת השגחה.'}),action('give-drink-unassessed','לתת משקה מתוק בלי לבדוק בליעה','treatment','מיותרת',score('priorities',-12),[],{critical:true,result:'אין לתת דרך הפה לפני וידוא הכרה ויכולת בליעה.'}),action('reassess','הערכה חוזרת ומדידת סוכר','reassessment','חובה',score('reassessment',12),['reassessed','improved'],{requires:['treated'],criticalOmission:true,result:'יש שיפור קליני; סוכר חוזר 82 mg/dL.'}),action('private-car','להציע פינוי ברכב פרטי','transport','מיותרת',score('priorities',-8),[],{critical:true,result:'מטופל שזקוק לטיפול ולניטור מפנים באמבולנס, לא ברכב פרטי.'}),action('prepare-transport','הכנה לפינוי והמשך ניטור','transport','מומלצת',score('priorities',6),['transport-ready'],{result:'המטופלת מוכנה לפינוי תחת ניטור.'})],
 events:[{id:'hypo-worsens',trigger:{interactionsAtLeast:9,missingFacts:['treated']},change:{consciousness:'מנומנמת; AVPU=V',addFacts:['deteriorated']},expectedAction:'glucose',criticalTimeout:'עדיפות מיידית',feedback:'ההיפוגליקמיה לא טופלה וההכרה הידרדרה. יש להעריך ABC ויכולת בליעה מחדש, להזעיק ALS ולהימנע ממתן דרך הפה אם אינה מגינה על נתיב האוויר.'}],
 expectedPath:{principles:[['ppe','scan-scene'],['airway','breathing','circulation','neuro'],['glucose','swallow'],['oral-glucose'],['conditions','insulin-details','food'],['reassess','prepare-transport']],requiredFacts:['scene-safe','airway-open','breathing-ok','glucose-low','swallow-ok','treated','reassessed'],acceptableAlternatives:[['chief','onset'],['food','activity']]},scoring:{max:{safety:15,primary:30,emergency:15,priorities:29,anamnesis:28,followup:0,reassessment:12}},feedback:{explanations:{glucose:'שינוי התנהגות ועור קר ולח מחייבים לחשוב על היפוגליקמיה ולבדוק סוכר.',swallow:'לפני מתן פומי חייבים לוודא הכרה ויכולת בליעה.',reassess:'לאחר טיפול בודקים שוב הכרה, ABC ומדדים.'}}
},
{
 id:'stroke-02',internalName:'wake-up-stroke',category:'נוירולוגיה ושבץ',difficulty:'בינוני',duration:'10–12 דקות',learningObjectives:['זיהוי FAST חיובי','קביעת זמן נראה לאחרונה תקין','שלילת היפוגליקמיה כחיקוי שבץ','פינוי דחוף ודיווח מוקדם'],courseTopics:['2-1 אנמנזה וגישה לחולה','2-3 מצבי חירום נוירולוגיים'],
 scene:{dispatchReason:'בלבול וקושי בדיבור',location:'מטבח בבית פרטי',shortDescription:'בן הזוג ממתין ליד הדלת. המטופל יושב על כיסא במטבח.',patientCount:1,preArrivalInfo:'גבר בן 68, בהכרה, קושי בדיבור מהבוקר.',immediateView:'זווית הפה השמאלית שמוטה והוא מתקשה להשלים משפט.'},
 safety:{existingHazards:['שטיח מקופל בדרך למטופל'],distractors:['אין ריח גז','אין סימני אלימות'],ppe:['כפפות'],requiredActions:['ppe','scan-scene'],additionalResources:['ALS','פינוי דחוף לבית חולים מתאים'],criticalMistakes:['give-food']},
 patient:{age:68,chiefComplaint:'קושי בדיבור וחולשה ביד ימין',consciousness:'ערני, AVPU=A',behavior:'מתוסכל אך משתף פעולה',appearance:'זווית פה שמאל שמוטה',findings:['דיבור משובש','צניחת יד ימין'],vitals:{respiratoryRate:'16',pulse:'88 סדיר',bloodPressure:'178/96',spo2:'96%',glucose:'112 mg/dL'},history:{conditions:['יתר לחץ דם','פרפור פרוזדורים'],medications:['תרופה ללחץ דם','מדלל דם — שם לא ידוע'],allergies:'אין ידועות',lastMeal:'אמש',events:'נראה תקין לאחרונה ב־23:00; התעורר עם הסימנים ב־06:40'}},
 facts:{'gloves-on':'כפפות נלבשו','scene-safe':'הזירה בטוחה; השטיח הוזז','airway-open':'נתיב אוויר פתוח','breathing-ok':'נשימה 16, סטורציה 96%','circulation':'דופק 88 סדיר, ל״ד 178/96','fast-positive':'FAST חיובי: צניחת פנים, חולשת יד ימין ודיבור משובש','glucose-normal':'סוכר 112 mg/dL','last-known-well':'נראה לאחרונה תקין ב־23:00 לפני השינה','anticoagulant':'נוטל מדלל דם, שם לא ידוע','als-called':'ALS הוזעק ונמסר חשד לשבץ','urgent-transport':'הוכן פינוי דחוף לבית חולים מתאים','reassessed':'הערכה חוזרת: ללא שינוי ב־ABC; החולשה נמשכת'},
 primaryAssessment:[action('airway','הערכת נתיב אוויר','primary','חובה',score('primary',7),['airway-open'],{criticalOmission:true,result:'נתיב האוויר פתוח; הדיבור משובש.'}),action('breathing','הערכת נשימה וסטורציה','primary','חובה',score('primary',7),['breathing-ok'],{result:'16 נשימות בדקה, סטורציה 96%.'}),action('circulation','דופק ולחץ דם','primary','חובה',score('primary',6),['circulation'],{result:'דופק 88 סדיר; לחץ דם 178/96.'}),action('fast','ביצוע FAST','primary','חובה',score('emergency',16),['fast-positive'],{criticalOmission:true,result:'פנים: צניחה; ידיים: יד ימין צונחת; דיבור: משובש.'}),action('glucose','בדיקת סוכר','primary','חובה',score('emergency',8),['glucose-normal'],{criticalOmission:true,result:'112 mg/dL — היפוגליקמיה אינה מסבירה את התמונה.'})],
 anamnesis:[question('chief','מה קרה היום?','תלונה עיקרית','המטופל מנסה לענות אך הדיבור אינו ברור. בן הזוג: ״קם ככה מהמיטה״.','חשובה',4,['woke-symptoms']),question('onset','מתי התחילו הסימנים?','מחלה נוכחית','״שמתי לב כשקם ב־06:40.״','חשובה',5,['wake-time'],{unlocks:['last-well']}),question('last-well','מתי נראה לאחרונה ללא הסימנים?','שאלת המשך','״אתמול ב־23:00, לפני שהלכנו לישון, היה רגיל לגמרי.״','חשובה',7,['last-known-well'],{condition:{question:'onset'},score:score('followup',7)}),question('meds','אילו תרופות הוא נוטל?','SAMPLE','״ללחץ דם וגם מדלל דם, איני זוכר את השם.״','חשובה',4,['anticoagulant'],{unlocks:['last-dose']}),question('last-dose','מתי נלקח מדלל הדם לאחרונה?','שאלת המשך','״אתמול בערב, כמו תמיד.״','משלימה',3,['anticoagulant-last-night'],{condition:{question:'meds'},score:score('followup',3)}),question('seizure','היו פרכוסים או אובדן הכרה?','אבחנה מבדלת','״לא.״','משלימה',3,['no-seizure']),question('trauma','הייתה נפילה או חבלת ראש?','אבחנה מבדלת','״לא.״','חשובה',3,['no-trauma']),question('vision','יש טשטוש, כפל ראייה או אובדן שדה ראייה?','נוירולוגיה','המטופל מצביע שמאלה; קשה לקבל תשובה מלאה.','משלימה',2,['vision-unclear']),question('smoking','כמה שנים אתה מעשן?','רקע','״הפסיק לפני עשור.״','לא רלוונטית',0,['former-smoker'])],
 actions:[action('ppe','לבישת כפפות','safety','חובה',score('safety',7),['gloves-on'],{result:'הצוות ממוגן.'}),action('scan-scene','סריקת הזירה והסרת מכשול','safety','חובה',score('safety',7),['scene-safe'],{result:'מטופל אחד; השטיח המקופל הוזז.'}),action('call-als','הזעקת ALS ודיווח על FAST חיובי','resources','חובה',score('priorities',12),['als-called'],{requires:['fast-positive'],criticalOmission:true,result:'המוקד מעודכן; צוות ALS בדרך.'}),action('urgent-transport','הכנה לפינוי דחוף ודיווח מוקדם','transport','חובה',score('priorities',14),['urgent-transport'],{requires:['fast-positive'],criticalOmission:true,result:'מתחילים פינוי דחוף לבית חולים מתאים.'}),action('give-food','לתת אוכל כי לא אכל מאז אמש','treatment','מיותרת',score('priorities',-14),[],{critical:true,result:'אין לתת אוכל בחשד לשבץ והפרעת בליעה אפשרית.'}),action('wait-symptoms','להמתין ולראות אם הסימנים חולפים','transport','מיותרת',score('priorities',-15),[],{critical:true,result:'גם TIA דורש אותה גישת פינוי דחופה; זמן מוח.'}),action('reassess','הערכת ABC ונוירולוגיה חוזרת','reassessment','חובה',score('reassessment',10),['reassessed'],{result:'אין שינוי ב־ABC; החסר הנוירולוגי נמשך.'})],
 events:[{id:'transport-delay',trigger:{interactionsAtLeast:7,missingFacts:['urgent-transport']},change:{addFacts:['delay-warning']},expectedAction:'urgent-transport',criticalTimeout:'עדיפות גבוהה',feedback:'נאסף מידע רב אך הפינוי טרם החל. בחשד לשבץ לא מעכבים פינוי לצורך השלמת כל השאלות.'}],expectedPath:{principles:[['ppe','scan-scene'],['airway','breathing','circulation'],['fast','glucose'],['onset','last-well'],['call-als','urgent-transport'],['meds','reassess']],requiredFacts:['scene-safe','fast-positive','glucose-normal','last-known-well','als-called','urgent-transport'],acceptableAlternatives:[['onset','chief']]},scoring:{max:{safety:14,primary:20,emergency:24,priorities:26,anamnesis:21,followup:10,reassessment:10}},feedback:{explanations:{fast:'FAST חיובי מחייב התייחסות כשבץ עד שיוכח אחרת.',glucose:'היפוגליקמיה עלולה לחקות שבץ ולכן בודקים סוכר.','last-well':'בשבץ יקיצה הזמן החשוב הוא הפעם האחרונה שבה נראה תקין.'}}
},
{
 id:'anaphylaxis-03',internalName:'restaurant-anaphylaxis',category:'נשימה ואנפילקסיס',difficulty:'מתקדם',duration:'10–13 דקות',learningObjectives:['זיהוי אנפילקסיס רב־מערכתי','תעדוף אדרנלין IM לפי פרוטוקול','זיהוי הידרדרות נשימתית והמודינמית','הערכה חוזרת ושקילת מנה נוספת'],courseTopics:['2-1 אנמנזה וגישה לחולה','2-5 מצבי חירום נשימתיים'],
 scene:{dispatchReason:'קוצר נשימה ופריחה',location:'מסעדה',shortDescription:'הצוות מפנה עבורכם מעבר לשולחן. המטופלת יושבת זקופה ומגרדת את צווארה.',patientCount:1,preArrivalInfo:'בת 31, קוצר נשימה שהחל בזמן הארוחה.',immediateView:'שפתיה נפוחות, פריחה בצוואר, והיא מצליחה לומר רק מילים בודדות.'},
 safety:{existingHazards:['צפיפות ושברי כוס ליד הכיסא'],distractors:['אין עשן','אין חומר כימי נשפך'],ppe:['כפפות'],requiredActions:['ppe','scan-scene'],additionalResources:['ALS באופן מיידי'],criticalMistakes:['delay-adrenaline']},
 patient:{age:31,chiefComplaint:'קוצר נשימה, נפיחות וגרד',consciousness:'ערנית וחרדה, AVPU=A',behavior:'מתקשה לדבר, מצביעה על הצוואר',appearance:'סומק, אורטיקריה ונפיחות בשפתיים',findings:['צפצופים דו־צדדיים','קול צרוד','מילים בודדות'],vitals:{respiratoryRate:'30, מאומץ',pulse:'126, חלש',bloodPressure:'86/54',spo2:'91%'},history:{conditions:['אלרגיה קשה לשומשום'],medications:['מזרק אדרנלין אישי בתיק'],allergies:'שומשום',lastMeal:'הארוחה הנוכחית',events:'אכלה רוטב חדש 8 דקות לפני תחילת הסימנים'}},
 facts:{'gloves-on':'כפפות נלבשו','scene-safe':'הזירה בטוחה לאחר פינוי שברי הזכוכית','airway-threat':'קול צרוד, נפיחות שפתיים וריור קל','breathing-distress':'30 נשימות מאומצות, צפצופים, סטורציה 91%','shock':'דופק 126 חלש, ל״ד 86/54','skin-signs':'אורטיקריה וסומק מפושטים','allergen':'אלרגיה לשומשום; אכלה רוטב חדש','epipen':'מזרק אדרנלין אישי נמצא בתיק','anaphylaxis':'פגיעה בעור/ריריות יחד עם נשימה ולחץ דם — חשד לאנפילקסיס','als-called':'ALS הוזעק','adrenaline-given':'אדרנלין IM ניתן לפי הפרוטוקול','oxygen':'חמצן ניתן לפי הפרוטוקול','positioned':'הושכבה בתנוחה מתאימה ונשמר חום גוף','reassessed':'בוצעה הערכה חוזרת לאחר הטיפול','partial-response':'אחרי 6 דקות: ל״ד 94/62, סטורציה 94%, עדיין צפצופים וקול צרוד'},
 primaryAssessment:[action('airway','הערכת נתיב אוויר וקול','primary','חובה',score('primary',8),['airway-threat'],{criticalOmission:true,result:'קול צרוד, נפיחות שפתיים וריור קל — איום על נתיב האוויר.'}),action('breathing','הערכת נשימה וסטורציה','primary','חובה',score('primary',8),['breathing-distress'],{criticalOmission:true,result:'30 נשימות מאומצות, צפצופים, סטורציה 91%.'}),action('circulation','דופק, עור ולחץ דם','primary','חובה',score('primary',8),['shock'],{criticalOmission:true,result:'דופק 126 חלש, ל״ד 86/54.'}),action('exposure','בדיקת עור וריריות','primary','מומלצת',score('emergency',6),['skin-signs'],{result:'אורטיקריה, סומק ונפיחות בשפתיים.'}),action('recognize-anaphylaxis','זיהוי אנפילקסיס','primary','חובה',score('emergency',14),['anaphylaxis'],{requires:['airway-threat','breathing-distress','shock'],criticalOmission:true,result:'התמונה מתאימה לאנפילקסיס עם פגיעה נשימתית והמודינמית.'})],
 anamnesis:[question('onset','מתי זה התחיל?','מחלה נוכחית','״לפני… כמה דקות…״','חשובה',4,['rapid-onset']),question('allergy','למה את אלרגית?','SAMPLE','״שומשום…״','חשובה',5,['allergen'],{unlocks:['exposure-food','epipen-question']}),question('exposure-food','מה אכלת סמוך להופעת הסימנים?','שאלת המשך','המלצר: ״טעמה רוטב חדש עם טחינה לפני כעשר דקות.״','חשובה',5,['allergen-exposure'],{condition:{question:'allergy'},score:score('followup',5)}),question('epipen-question','יש לך מזרק אדרנלין אישי?','שאלת המשך','המטופלת מצביעה על התיק. נמצא מזרק בתוקף.','חשובה',5,['epipen'],{condition:{question:'allergy'},score:score('followup',5)}),question('previous','קרה בעבר?','רקע רפואי','״כן… פעם… אדרנלין…״','משלימה',3,['prior-anaphylaxis']),question('meds','נטלת תרופה לפני שהגענו?','תרופות','״לא…״','משלימה',2,['no-treatment']),question('stomach','יש כאב בטן, בחילה או הקאה?','תסמינים נלווים','מהנהנת ומצביעה על הבטן.','משלימה',2,['gi-symptoms']),question('menu','איזו מנה הזמנת?','לא רלוונטי','המלצר מתחיל לפרט את כל התפריט.','לא רלוונטית',-2,[],{feedback:'יש לברר את האלרגן והזמן — לא את פרטי התפריט המלא.'})],
 actions:[action('ppe','לבישת כפפות','safety','חובה',score('safety',6),['gloves-on'],{result:'הצוות ממוגן.'}),action('scan-scene','פינוי צפיפות ושברי זכוכית','safety','חובה',score('safety',7),['scene-safe'],{result:'נוצר מרחב טיפול בטוח.'}),action('call-als','הזעקת ALS מיידית','resources','חובה',score('priorities',10),['als-called'],{criticalOmission:true,result:'ALS הוזעק.'}),action('adrenaline','מתן אדרנלין IM לפי הפרוטוקול','treatment','חובה',score('emergency',20),['adrenaline-given'],{requires:['anaphylaxis'],criticalOmission:true,result:'אדרנלין IM ניתן בירך לפי הפרוטוקול.'}),action('oxygen','מתן חמצן לפי הפרוטוקול','treatment','חובה',score('priorities',8),['oxygen'],{requires:['breathing-distress'],result:'חמצן ניתן בריכוז מתאים.'}),action('position','השכבה, הרמת רגליים אם מתאים ושמירת חום','treatment','מומלצת',score('priorities',7),['positioned'],{requires:['shock'],result:'המטופלת מושכבת בזהירות ונשמר חום הגוף.'}),action('delay-adrenaline','להמתין ל־ALS לפני אדרנלין','treatment','מיותרת',score('emergency',-20),[],{critical:true,result:'אין לעכב אדרנלין באנפילקסיס.'}),action('inhaler-only','להסתפק במשאף בגלל הצפצופים','treatment','מיותרת',score('priorities',-12),[],{critical:true,result:'צפצופים אינם מסבירים לחץ דם נמוך ונפיחות. יש לטפל באנפילקסיס.'}),action('reassess','הערכת ABC ומדדים חוזרת לאחר הטיפול','reassessment','חובה',score('reassessment',12),['reassessed','partial-response'],{requires:['adrenaline-given'],criticalOmission:true,result:'שיפור חלקי; עדיין צפצופים וצרידות.'}),action('consider-second-dose','שקילת מנה נוספת והתייעצות לפי הפרוטוקול','reassessment','מומלצת',score('reassessment',7),['second-dose-considered'],{requires:['partial-response'],result:'חלפו 5–10 דקות ואין שיפור מלא — נשקלת מנה נוספת.'}),action('urgent-transport','פינוי דחוף תוך המשך טיפול','transport','חובה',score('priorities',10),['urgent-transport'],{criticalOmission:true,result:'הפינוי הדחוף החל תוך ניטור וטיפול.'})],
 events:[{id:'airway-worsens',trigger:{interactionsAtLeast:8,missingFacts:['adrenaline-given']},change:{consciousness:'ערנית אך נעשית ישנונית',addFacts:['worsening-airway']},expectedAction:'adrenaline',criticalTimeout:'מיידי',feedback:'הצרידות מתחזקת, תנועת האוויר נחלשת והמטופלת נעשית ישנונית. האדרנלין התעכב.'}],expectedPath:{principles:[['ppe','scan-scene'],['airway','breathing','circulation'],['call-als','recognize-anaphylaxis'],['adrenaline','oxygen','position'],['allergy','exposure-food','epipen-question'],['reassess','consider-second-dose','urgent-transport']],requiredFacts:['scene-safe','airway-threat','breathing-distress','shock','anaphylaxis','adrenaline-given','als-called','reassessed','urgent-transport'],acceptableAlternatives:[['allergy','exposure-food']]},scoring:{max:{safety:13,primary:24,emergency:40,priorities:35,anamnesis:16,followup:10,reassessment:19}},feedback:{explanations:{adrenaline:'באנפילקסיס עם פגיעה נשימתית או המודינמית אדרנלין IM הוא הפעולה המרכזית ואין לעכבו.',reassess:'שיפור חלקי אינו סוף האירוע; יש לבדוק ABC ומדדים ולשקול מנה נוספת.','call-als':'האיום על נתיב האוויר וההלם מחייבים תגבור ופינוי דחוף.'}}
}
];
})();
